# Generated by Django 5.1.6 on 2025-04-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='info',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
