# Generated by Django 5.1.6 on 2025-04-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
