# Generated by Django 5.1.6 on 2025-04-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0006_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='totembo.product')),
            ],
            options={
                'verbose_name': 'Product2',
                'verbose_name_plural': 'Products2',
            },
            bases=('totembo.product',),
        ),
    ]
