# Generated by Django 5.1.6 on 2025-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0007_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
