# Generated by Django 5.1.6 on 2025-05-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0009_productchain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductChain',
        ),
    ]
