# Generated by Django 5.1.6 on 2025-05-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0011_chainproduct_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('gold', 'gold'), ('yellow', 'yellow'), ('black', 'black'), ('silver', 'silver')], default='gold', max_length=30),
        ),
    ]
