# Generated by Django 5.1.6 on 2025-05-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0012_product_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChainProduct',
        ),
    ]
