# Generated by Django 5.1.6 on 2025-05-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0015_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='products',
            new_name='product',
        ),
    ]
