# Generated by Django 5.1.6 on 2025-06-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0016_rename_products_like_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('quartz edition', 'quartz edition'), ('chain edition', 'chain edition'), ('automatic edition', 'automatic edition')], default='quartz edition', max_length=30),
        ),
    ]
